name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build application
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-guestbook-artifacts
          path: |
            frontend/build/
            backend/build/
