name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build application
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-guestbook-artifacts
          path: |
            go-guestbook/bin/
